### PR TITLE
fix(vesting): improvements in accounting after slashing events

### PR DESCRIPTION
**Pull request by JimLarson**
Latest improvements from 4085-true-vesting.

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
LGTM!  Some minor typos in comments, but nothing worth diverging from `4085-true-vesting`.

Let's postpone merging until we have the go-ahead.

**Comment by michaelfig** [comment]
Protobuf breakage is expected (removing the obsoleted `combined_periods` field before it was landed in a release), so that test failure is irrelevant.

**Comment by JimLarson** [comment]
Didn't we have a label to expect proto compatibility breakage?

**Comment by michaelfig** [comment]
> Didn't we have a label to expect proto compatibility breakage?

Just in Agoric SDK.

**Review by michaelfig — APPROVED** [review]
Good stuff!

**Pull request merged**
