### PR TITLE
feat!: have tx gov submit-proposal accept either new or legacy syntax

### PR DESCRIPTION
**Pull request by JimLarson**
Have submit-legacy-proposal be an alias for submit-proposal. Invocations of the legacy syntax should either upgrade to the new syntax, or explicitly use submit-legacy-proposal. When all legacy usages have so migrated, this change can be dropped. See Agoric/agoric-sdk#8871.

## Description

Refs: #8871

Alter the `tx gov submit-proposal` command so that it works either with the new or legacy syntax, and also alias it as `submit-legacy-proposal`. Users of the legacy command will continue to work as-is, but over time they should either explicitly use `submit-legacy-proposal`, or upgrade to the new syntax. When all call sites have done one or the other of these choices, we can drop our modification to this command.

The slight limitation of this approach is that you cannot name the new-syntax JSON file the same as one of the legacy subcommands.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [x] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [x] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [x] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by JimLarson** [comment]
No new tests since this is meant to be backward-compatible.

**Review by dckc — COMMENTED** [review]
It would take me a while to study this enough to give an "I understand this well enough to help maintain it" review.

If there's some urgency and an "I don't see any problems" approval is useful, LMK.

**Comment by JimLarson** [comment]
The golangci-lint failure is expected.

**Review by michaelfig — APPROVED** [review]
LGTM!  Well done.

**Pull request merged**
